const SUPABASE_URL="https://nrchmdphzwgntsgjesqn.supabase.co",SUPABASE_KEY="sb_publishable_gF1GO41QQznJcDycpLBjkw_7fn_Q-hO";
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY),carId=new URLSearchParams(location.search).get("id"),money=v=>new Intl.NumberFormat("ru-RU").format(Number(v||0))+" ₽",date=v=>new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(v));
let car,expenseTotal=0,dialogMode="";
const el=id=>document.getElementById(id),set=(id,value)=>el(id).textContent=value;
function toast(message){set("toast",message);el("toast").classList.add("show");setTimeout(()=>el("toast").classList.remove("show"),2500)}
async function history(action,details=""){await db.from("car_history").insert({car_id:String(carId),action,details})}
async function loadCar(){
 if(!carId){set("title","Автомобиль не выбран");return}
 const{data,error}=await db.from("cars").select("*").eq("id",carId).single();if(error){set("title","Автомобиль не найден");set("meta",error.message);return}car=data;
 set("title",`${car.brand||""} ${car.model||""}`.trim()||"Без названия");set("meta",`${car.year||"—"} • ${Number(car.mileage||0).toLocaleString("ru-RU")} км • VIN ${car.vin||"—"}`);
 ["brand","model","vin","year","status"].forEach(k=>set(k,car[k]||"—"));set("location",car.location||car.current_location||"—");set("mileage",Number(car.mileage||0).toLocaleString("ru-RU")+" км");set("purchase",money(car.purchase_price));set("sale",money(car.sale_price));set("saleTop",money(car.sale_price));
 const since=car.status_changed_at||car.updated_at||car.created_at;if(since){set("daysCount",Math.max(0,Math.floor((Date.now()-new Date(since))/(864e5))));set("daysLabel",/пути|транзит/i.test(car.status||"")?"Дней в пути":/склад|налич/i.test(car.status||"")?"Дней на складе":"Дней в статусе")}
 await Promise.all([loadExpenses(),loadFiles(),loadRoute(),loadHistory()]);updateMoney();
}
function updateMoney(){set("expenses",money(expenseTotal));set("costPrice",money(Number(car?.purchase_price||0)+expenseTotal));set("margin",money(Number(car?.sale_price||0)-Number(car?.purchase_price||0)-expenseTotal))}
async function loadExpenses(){const{data}=await db.from("expenses").select("*").eq("car_id",carId).order("created_at",{ascending:false});expenseTotal=(data||[]).reduce((s,x)=>s+Number(x.amount||0),0);el("expenseList").innerHTML=(data||[]).map(x=>`<div class="record"><span>${x.name||x.category||"Расход"}<small>${x.created_at?date(x.created_at):""}</small></span><b>${money(x.amount)}</b></div>`).join("")||'<div class="empty">Расходов пока нет</div>'}
async function loadFiles(){const{data}=await db.from("car_files").select("*").eq("car_id",String(carId)).order("created_at",{ascending:false});const photos=(data||[]).filter(x=>x.file_type==="photo"),docs=(data||[]).filter(x=>x.file_type!=="photo");el("photos").innerHTML=photos.map(x=>`<a href="${db.storage.from("car-files").getPublicUrl(x.path).data.publicUrl}" target="_blank"><img src="${db.storage.from("car-files").getPublicUrl(x.path).data.publicUrl}" alt=""></a>`).join("")||'<div class="empty">Фото пока нет</div>';el("documents").innerHTML=docs.map(x=>`<a class="record file-link" href="${db.storage.from("car-files").getPublicUrl(x.path).data.publicUrl}" target="_blank"><span>📄 ${x.name}<small>${date(x.created_at)}</small></span><b>Открыть</b></a>`).join("")||'<div class="empty">Документов пока нет</div>'}
async function uploadFiles(files,type){if(!files.length)return;toast("Загрузка…");for(const file of files){const clean=file.name.replace(/[^a-zA-Zа-яА-Я0-9._-]/g,"_"),path=`${carId}/${Date.now()}_${clean}`;const{error}=await db.storage.from("car-files").upload(path,file);if(error){toast("Ошибка: "+error.message);continue}await db.from("car_files").insert({car_id:String(carId),name:file.name,path,file_type:type,mime_type:file.type});await history(type==="photo"?"Загружено фото":"Загружен документ",file.name)}toast("Файлы загружены");await Promise.all([loadFiles(),loadHistory()])}
async function loadRoute(){const{data}=await db.from("route_events").select("*").eq("car_id",String(carId)).order("event_date",{ascending:false});el("routeList").innerHTML=(data||[]).map(x=>`<div class="timeline-item"><b>${x.location}</b><span>${x.status||"Событие маршрута"} · ${date(x.event_date)}</span></div>`).join("")||'<div class="empty">Маршрут пока не заполнен</div>'}
async function loadHistory(){const{data}=await db.from("car_history").select("*").eq("car_id",String(carId)).order("created_at",{ascending:false}).limit(30);el("historyList").innerHTML=(data||[]).map(x=>`<div class="timeline-item"><b>${x.action}</b><span>${x.details||""} · ${date(x.created_at)}</span></div>`).join("")||'<div class="empty">История пока пуста</div>'}
function openDialog(mode){dialogMode=mode;set("dialogTitle",mode==="expense"?"Добавить расход":"Добавить событие маршрута");el("dialogFields").innerHTML=mode==="expense"?'<label>Название<input name="name" required placeholder="Доставка, таможня…"></label><label>Сумма<input name="amount" type="number" min="0" required></label>':'<label>Местоположение<input name="location" required placeholder="Бишкек"></label><label>Статус<input name="status" placeholder="Прибыл на склад"></label><label>Дата<input name="event_date" type="date" required></label>';if(mode==="route")el("quickForm").elements.event_date.value=new Date().toISOString().slice(0,10);el("formDialog").showModal()}
el("quickForm").addEventListener("submit",async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(dialogMode==="expense"){const{error}=await db.from("expenses").insert({car_id:carId,name:f.name,amount:Number(f.amount)});if(error)return toast("Ошибка: "+error.message);await history("Добавлен расход",`${f.name}: ${money(f.amount)}`);await loadExpenses();updateMoney()}else{await db.from("route_events").insert({...f,car_id:String(carId)});await history("Обновлён маршрут",`${f.location}: ${f.status||"событие"}`);await loadRoute()}await loadHistory();el("formDialog").close();e.target.reset();toast("Сохранено")});
el("expenseBtn").onclick=()=>openDialog("expense");el("expenseAddBtn").onclick=()=>openDialog("expense");el("routeBtn").onclick=()=>openDialog("route");el("routeAddBtn").onclick=()=>openDialog("route");el("photoInput").onchange=e=>uploadFiles([...e.target.files],"photo");el("documentInput").onchange=e=>uploadFiles([...e.target.files],"document");loadCar();
