-- Выполнить один раз в Supabase → SQL Editor.
alter table if exists public.expenses add column if not exists name text;
alter table if exists public.expenses add column if not exists created_at timestamptz not null default now();
create table if not exists public.car_files (id bigint generated by default as identity primary key,car_id text not null,name text not null,path text not null,file_type text not null default 'document',mime_type text,created_at timestamptz not null default now());
create table if not exists public.car_history (id bigint generated by default as identity primary key,car_id text not null,action text not null,details text,created_at timestamptz not null default now());
create table if not exists public.route_events (id bigint generated by default as identity primary key,car_id text not null,location text not null,status text,event_date date not null default current_date,created_at timestamptz not null default now());
insert into storage.buckets (id,name,public) values ('car-files','car-files',true) on conflict (id) do update set public=true;
alter table public.car_files enable row level security;alter table public.car_history enable row level security;alter table public.route_events enable row level security;
drop policy if exists "crm car_files all" on public.car_files;drop policy if exists "crm car_history all" on public.car_history;drop policy if exists "crm route_events all" on public.route_events;
create policy "crm car_files all" on public.car_files for all using (true) with check (true);create policy "crm car_history all" on public.car_history for all using (true) with check (true);create policy "crm route_events all" on public.route_events for all using (true) with check (true);
drop policy if exists "crm expenses all" on public.expenses;
create policy "crm expenses all" on public.expenses for all using (true) with check (true);
drop policy if exists "crm storage upload" on storage.objects;drop policy if exists "crm storage read" on storage.objects;
create policy "crm storage upload" on storage.objects for insert with check (bucket_id='car-files');create policy "crm storage read" on storage.objects for select using (bucket_id='car-files');
